on:
  push:
    branches: 
      - main
name: ğŸš€ Auto Deploy
jobs:
  web-deploy:
    name: ğŸ‰ Auto Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Checkout ( Get latest code )
      uses: actions/checkout@v4.1.1

    - name: ğŸ“‚ Sync files
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --delete --exclude=".git" --exclude=".github"
        path: /
        remote_path: ${{ secrets.DEPLOY_PATH }}
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_port: ${{ secrets.DEPLOY_PORT }}
        remote_key: ${{ secrets.DEPLOY_KEY }}

    # - name: âš™ï¸ Initialize SSH
    #   uses: webfactory/ssh-agent@v0.9.0
    #   with:
    #     ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    # - name: ğŸš‚ Deploy and run Composer
    #   run: | 
    #     ssh -o StrictHostKeyChecking=no -p ${{ secrets.DEPLOY_PORT }} ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} 'mv ${{ secrets.DEPLOY_PATH }}/public ${{ secrets.DEPLOY_PATH }}/public_html && cd ${{ secrets.DEPLOY_PATH }} && composer2 install && ln -s ${{ secrets.DEPLOY_PATH }}/storage/app/public ${{ secrets.DEPLOY_PATH }}/public_html/storage'